---
- name: Configure Dnsmasq on Host2
  hosts: dns_servers
  become: yes
  tasks:

    - name: Deconflict systemd-resolve by disabling/stopping the daemon
      ansible.builtin.systemd:
        name: systemd-resolved.service
        become: yes
        state: stopped

    - name: Update Package lists
      apt:
        become: yes
        update_cache: yes
    
    - name: Ensure latest Dnsmasq package
      ansible.builtin.package:
        become: yes
        name:
          - dnsmasq
        state: latest

    - name: Configure default dnsmasq port
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.conf
        regexp: 'port='
        insertafter: '#port='
        line: 53
