---
- name: Configure Dnsmasq on Host2
  hosts: dns_servers
  become: yes
  tasks:

    - name: Deconflict systemd-resolve by disabling/stopping the daemon
      ansible.builtin.systemd:
        name: systemd-resolved.service
        state: started

    - name: Update Package lists
      become: yes
      apt:
        update_cache: yes
    
    - name: Ensure latest Dnsmasq package
      become: yes
      ansible.builtin.package:
        name:
          - dnsmasq
        state: latest

    - name: Configure default dnsmasq port
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.conf
        regexp: 'port='
        insertafter: '#port='
        line: Port=53

    - name: Template a file to /etc/file.conf
      become: yes
      ansible.builtin.template:
        src: ./Templates/dnsmasq.conf
        dest: /etc/dnsmasq.conf
        owner: root
        group: root
        mode: '0644'