- name: Harden Linux VMs
  hosts: all
  become: yes
  tasks:
  - name: Run equivalent of apt-get update
    apt:
      update_cache: yes
  - name: Upgrade all packages to latest versions
    apt:
      name: "*"
      state: latest