---
- name: Harden all systems
  hosts: controller
  become: yes
  tasks:
    - name: Ensure latest Git and Ansible packages
      become: yes
      ansible.builtin.package:
        name:
          - ansible
          - git
        state: latest

- name: STIG Hardening
  hosts: hosts
  vars:
    ansible_become: true
  roles:
  - role: ansible-hardening
    vars:
      stig_version: rhel7
      security_enable_pwquality_password_set: yes
      security_password_max_lifetime_days: 90