- name: Harden Linux VMs
  hosts: all
  become: yes
  tasks:
  - name: Run equivalent of apt-get update
    apt:
      update_cache: yes
  - name: Upgrade all packages to latest versions
    apt:
      name: "*"
      state: latest
  - name: Add the user "'tyr' with a primary group 'admin'
    ansible.builtin.user:
        name: tyr
        group: admin
        
