---
- name: Create Samba share on Host2 accessible to Host3
  hosts: file_servers
  become: yes
  tasks:

    - name: Update Packages
      apt:
        update_cache: yes
      tags:
      - update

    - name: Ensure latest Samba package
      ansible.builtin.package:
        name:
          - samba
        state: latest

    - name: Create a shared folder
      community.general.udm_share:
        name: Samba_share
        path: /home
        host: file_servers
        sambaName: Home
        state: present
        ou: tyr