---
- name: Create Samba share on Host2 accessible to Host3
  hosts: file_servers
  become: yes
  tasks:

  - name: Update Packages
    apt:
      update_cache: yes
    tags:
    - update

  - name: Ensure latest Samba package
    ansible.builtin.package:
      name:
        - samba
      state: latest

  - name: Create directory for share
    ansible.builtin.file:
      path: /home/sambashare
      state: directory
      owner: tyr-admin
      mode: '0755'

  - name: Update Samba configuration file
    ansible.builtin.blockinfile:
      path: /etc/samba/smb.conf
      backup: yes
      insertafter: EOF
      block: |
        [sambashare]
          comment = Samba on Ubuntu
          path = /home/username/sambashare
          read only = no
          browsable = yes

  - name: Restart samba service
    ansible.builtin.systemd:
       name: smbd.service
       state: restarted

- name: Configure Samba clients
  hosts: samba_clients
  become: yes
  tasks:

  - name: Mount Samba share from Host2
    mount:
      state: "mounted"
      fstype: "cifs"
      name: /mnt/sambashare
      src: "//10.1.2.5/sambashare"
      opts: "credentials=/root/.smb_passwords,file_mode=0644,dir_mode=0755,gid=root,uid=root"