---
- name: Create Samba share on Host2
  hosts: file_servers
  become: yes
  tasks:

  - name: Update Packages
    apt:
      update_cache: yes
    tags:
    - update

  - name: Ensure latest Samba package
    ansible.builtin.package:
      name:
        - samba
      state: latest

  - name: Create directory for share
    ansible.builtin.file:
      path: /home/sambashare
      state: directory
      owner: tyr-admin
      mode: '0755'

  - name: Ensure group "somegroup" exists
    ansible.builtin.group:
      name: sambausers
      state: present

  - name: Add user to samba group
    ansible.builtin.user:
      name: tyr-admin
      groups: sambausers
      append: yes

  - name: Update Samba configuration file
    ansible.builtin.blockinfile:
      path: /etc/samba/smb.conf
      backup: yes
      insertafter: EOF
      block: |
        [sambashare]
          comment = Samba on Ubuntu
          path = /home/username/sambashare
          read only = no
          browsable = yes
          valid users = tyr-admin @sambausers

  - name: Restart samba service
    ansible.builtin.systemd:
       name: smbd.service
       state: restarted

  - name: Configure Firewall to allow Samba
    community.general.ufw:
      rule: allow
      name: Samba
  
- name: Configure Samba clients
  hosts: samba_clients
  become: yes
  tasks:

  - name: Install smbclient
    apt:
      name: smbclient
      state: present

  # - name: Mount Samba share from Host2
  #   mount:
  #     src: //path/to/windows/share
  #     path: /mnt
  #     fstype: cifs
  #     opts: 'username=tyr-admin,password=password'
  #     state: mounted
  #   become: true
